[package]
name = "bashrs"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["macros"]

[dependencies]
clap = { version = "4", features = ["derive"] }
bashrs-macros = { path = "macros" }
table_formatter = { git = "https://github.com/SirHexa10t/table_formatter.git", branch = "main" }
synoptic = "2"
libc = "0.2"
