#!/usr/bin/env bash
set -e  # exit (do not continue) when any step fails

cargo build --release

cargo install --path . --bin bashrs  # copies the main binary (instead of all) into:  ~/.cargo/bin/
echo "Installed bashrs at ~/.cargo/bin"

AUTOGEN_FILENAME="auto_generated.bashrs"
AUTOGEN_FILE="$HOME/$AUTOGEN_FILENAME"
./target/release/generate_sourceable > "$AUTOGEN_FILE"  # use 2nd binary to generate functions in namespace
echo "Generated $AUTOGEN_FILE"

BASHRC="$HOME/.bashrc"
SOURCE_LINE="source \"$AUTOGEN_FILENAME\""
if grep -qF "$SOURCE_LINE" "$BASHRC"; then  # is sourcing already within .bashrc?
    echo "$AUTOGEN_FILENAME is already sourced in $BASHRC"
else
    echo -e "\n$SOURCE_LINE  # source bashrs autogenerated function calls\n" >> "$BASHRC"
    echo "Added source line to $BASHRC"
fi

