//! Commands for managing bashrs itself.

#[bashrs_macros::category(command = BashrsCommand, prefix = "bashrs_")]
mod commands {
    use crate::categories::args::NoArgs;
    use std::path::{Path, PathBuf};
    use std::process::Command;

    /// Recompile and reinstall bashrs by running the project's COMPILE.sh
    #[after("session_new")] // start a fresh shell after a successful compile
    pub fn compile(_args: NoArgs) {
        // The project path is captured at build time (`CARGO_MANIFEST_DIR`), so
        // if the project was moved — or COMPILE.sh renamed — since the last
        // compile, report that clearly instead of failing obscurely.
        //
        // Every failure path exits non-zero so the wrapper's `&& session_new` is
        // skipped: the shell should only restart after a real, successful compile.
        let project = Path::new(env!("CARGO_MANIFEST_DIR"));
        let script = match _locate_script(project) {
            Ok(script) => script,
            Err(msg) => {
                eprintln!("bashrs_compile: {msg}");
                std::process::exit(1);
            }
        };
        match Command::new("bash").arg(&script).current_dir(project).status() {
            // Signal the wrapper to start a fresh session — only on a real success.
            Ok(status) if status.success() => std::process::exit(crate::categories::RELOAD_EXIT_CODE),
            Ok(status) => {
                eprintln!("bashrs_compile: COMPILE.sh exited with status: {status}");
                std::process::exit(1);
            }
            Err(err) => {
                eprintln!("bashrs_compile: could not launch COMPILE.sh: {err}");
                std::process::exit(1);
            }
        }
    }

    /// Print the autogenerated source file, noting where it lives
    pub fn sourcefile(_args: NoArgs) {
        let path = _sourcefile_path();
        match std::fs::read_to_string(&path) {
            Ok(contents) => {
                print!("{contents}"); // cat: emit the file verbatim
                if !contents.ends_with('\n') {
                    println!();
                }
                println!("# source file: {}", path.display());
            }
            Err(err) => eprintln!("bashrs_sourcefile: cannot read {}: {err}", path.display()),
        }
    }

    /// Resolve the project's `COMPILE.sh`, or explain why it can't be found.
    fn _locate_script(project: &Path) -> Result<PathBuf, String> {
        if !project.is_dir() {
            return Err(format!(
                "project directory not found: {} — moved or removed since the last compile",
                project.display()
            ));
        }
        let script = project.join("COMPILE.sh");
        if !script.is_file() {
            return Err(format!(
                "COMPILE.sh not found: {} — renamed or removed",
                script.display()
            ));
        }
        Ok(script)
    }

    /// Path to the autogenerated source file (`~/.bashrs/sourcefile.sh`).
    fn _sourcefile_path() -> PathBuf {
        let home = std::env::var_os("HOME").map(PathBuf::from).unwrap_or_default();
        home.join(".bashrs").join("sourcefile.sh")
    }

    #[cfg(test)]
    mod tests {
        use super::*;

        #[test]
        fn reports_a_missing_project_directory() {
            let err = _locate_script(Path::new("/no/such/bashrs/project")).unwrap_err();
            assert!(err.contains("project directory not found"), "got: {err}");
        }

        #[test]
        fn reports_a_missing_compile_script() {
            // `src/` exists but holds no COMPILE.sh — exercises the second check.
            let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("src");
            let err = _locate_script(&dir).unwrap_err();
            assert!(err.contains("COMPILE.sh not found"), "got: {err}");
        }

        #[test]
        fn resolves_the_script_when_present() {
            let project = Path::new(env!("CARGO_MANIFEST_DIR"));
            assert_eq!(_locate_script(project).unwrap(), project.join("COMPILE.sh"));
        }

        #[test]
        fn sourcefile_lives_under_bashrs_home() {
            assert!(_sourcefile_path().ends_with(".bashrs/sourcefile.sh"));
        }
    }
}
