//! Commands for managing bashrs itself.

#[bashrs_macros::category(command = BashrsCommand, prefix = "bashrs_")]
mod commands {
    use crate::conf::config_file;
    use crate::support::args::NoArgs;
    use crate::support::{exec, theme_code};
    use clap::Args;
    use std::path::{Path, PathBuf};
    use std::process::Command;

    /// Everything after the command, forwarded verbatim to COMPILE.sh — the script owns its
    /// flag set (and rejects unknowns loudly), so nothing needs re-declaring here when it
    /// grows one. The cost: clap can't list or TAB-complete the flags; COMPILE.sh's header
    /// documents them (currently --use-stable-cargo, --use-stable-carstay).
    #[derive(Args)]
    pub struct CompileArgs {
        /// Flags for COMPILE.sh (e.g. --use-stable-cargo, --use-stable-carstay — see its header)
        #[arg(trailing_var_arg = true, allow_hyphen_values = true)]
        args: Vec<String>,
    }

    /// Recompile and reinstall bashrs by running the project's COMPILE.sh
    #[after("session_new")] // start a fresh shell after a successful compile
    pub fn compile(_args: CompileArgs) {
        // The project path is captured at build time (`CARGO_MANIFEST_DIR`), so
        // if the project was moved — or COMPILE.sh renamed — since the last
        // compile, report that clearly instead of failing obscurely.
        //
        // Every failure path exits non-zero so the wrapper's `&& session_new` is
        // skipped: the shell should only restart after a real, successful compile.
        let project = Path::new(env!("CARGO_MANIFEST_DIR"));
        let script = match _locate_script(project, "COMPILE.sh") {
            Ok(script) => script,
            Err(msg) => {
                eprintln!("bashrs_compile: {msg}");
                std::process::exit(1);
            }
        };
        match Command::new("bash").arg(&script).args(&_args.args).current_dir(project).status() {
            // Signal the wrapper to start a fresh session — only on a real success.
            Ok(status) if status.success() => std::process::exit(crate::conf::RELOAD_EXIT_CODE),
            Ok(status) => {
                eprintln!("bashrs_compile: COMPILE.sh exited with status: {status}");
                std::process::exit(1);
            }
            Err(err) => {
                eprintln!("bashrs_compile: could not launch COMPILE.sh: {err}");
                std::process::exit(1);
            }
        }
    }

    /// Run the project's full test suite by running its TEST.sh — every category, the live and
    /// cookie-gated ones included (those self-skip where the machine's setup lacks the pieces)
    pub fn test(_args: NoArgs) {
        let project = Path::new(env!("CARGO_MANIFEST_DIR"));
        let script = match _locate_script(project, "TEST.sh") {
            Ok(script) => script,
            Err(msg) => {
                eprintln!("bashrs_test: {msg}");
                std::process::exit(1);
            }
        };
        match Command::new("bash").arg(&script).current_dir(project).status() {
            Ok(status) if status.success() => {}
            // TEST.sh's own summary already named what failed — just propagate the verdict.
            Ok(status) => std::process::exit(status.code().unwrap_or(1)),
            Err(err) => {
                eprintln!("bashrs_test: could not launch TEST.sh: {err}");
                std::process::exit(1);
            }
        }
    }

    /// Open the bashrs configuration file (~/.bashrs/configrs.toml), creating it on first use
    pub fn configure(_args: NoArgs) {
        let path = match config_file::ensure_current() {
            Ok(path) => path,
            Err(err) => return eprintln!("bashrs_configure: cannot create the config file: {err}"),
        };
        // `$EDITOR` when set (edits right here in the terminal); else the desktop opener —
        // `xdg-open` is Linux's `open` (a bare `open` is usually openvt, a console switcher).
        match std::env::var("EDITOR") {
            Ok(editor) if !editor.trim().is_empty() => {
                exec::run_reporting(editor.trim(), [&path]);
            }
            _ => {
                exec::run_reporting("xdg-open", [&path]);
            }
        }
    }

    /// Print the autogenerated source file, noting where it lives
    pub fn sourcefile(_args: NoArgs) {
        let path = _sourcefile_path();
        match std::fs::read_to_string(&path) {
            Ok(contents) => {
                // Syntax-highlight the shell as we print it.
                let shown = theme_code::highlight(&contents, "sh");
                print!("{shown}");
                if !shown.ends_with('\n') {
                    println!();
                }
                println!(); // blank line to set the location note off from the file body
                println!("# source file: {}", path.display());
            }
            Err(err) => eprintln!("bashrs_sourcefile: cannot read {}: {err}", path.display()),
        }
    }

    /// Resolve `script` inside the project directory, or explain why it can't be found.
    fn _locate_script(project: &Path, script: &str) -> Result<PathBuf, String> {
        if !project.is_dir() {
            return Err(format!(
                "project directory not found: {} — moved or removed since the last compile",
                project.display()
            ));
        }
        let path = project.join(script);
        if !path.is_file() {
            return Err(format!("{script} not found: {} — renamed or removed", path.display()));
        }
        Ok(path)
    }

    /// Path to the autogenerated source file (`~/.bashrs/sourcefile.sh`).
    fn _sourcefile_path() -> PathBuf {
        crate::conf::bashrs_home().join("sourcefile.sh")
    }

    #[cfg(test)]
    mod tests {
        use super::*;

        #[test]
        fn reports_a_missing_project_directory() {
            let err =
                _locate_script(Path::new("/no/such/bashrs/project"), "COMPILE.sh").unwrap_err();
            assert!(err.contains("project directory not found"), "got: {err}");
        }

        #[test]
        fn reports_a_missing_script_by_its_name() {
            // `src/` exists but holds neither script — exercises the second check for both.
            let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("src");
            let err = _locate_script(&dir, "COMPILE.sh").unwrap_err();
            assert!(err.contains("COMPILE.sh not found"), "got: {err}");
            let err = _locate_script(&dir, "TEST.sh").unwrap_err();
            assert!(err.contains("TEST.sh not found"), "got: {err}");
        }

        #[test]
        fn resolves_the_scripts_when_present() {
            let project = Path::new(env!("CARGO_MANIFEST_DIR"));
            assert_eq!(_locate_script(project, "COMPILE.sh").unwrap(), project.join("COMPILE.sh"));
            assert_eq!(_locate_script(project, "TEST.sh").unwrap(), project.join("TEST.sh"));
        }

        #[test]
        fn sourcefile_lives_under_bashrs_home() {
            assert!(_sourcefile_path().ends_with(".bashrs/sourcefile.sh"));
        }
    }
}
