//! Text-lookup commands: the shell-history search (`hg`) and the loud all-caps deep searches — `GG`
//! (recursive search with `--delve` forced on) and `GGG` (`GG` plus `--save` and `-E` forced too).
//! This module also owns the runners the generated shortcut
//! families forward to — `_grep` for the `g` family and `_gg` for the `gg` family (both in
//! [`crate::categories::autogen_lookup`]) — plus [`gg_elevated_rescan`], the root re-scan routine.
//! Those live here, not in `support`, because the re-scan drives a `sudo` self-re-exec (generated by
//! [`macro@bashrs_macros::elevated`]) that reaches up to [`crate::run`], sitting above the `support`
//! search engines ([`streamgrep`](crate::support::streamgrep), [`treegrep`](crate::support::treegrep));
//! the shared argument structs are in [`crate::support::args`].

// `treegrep` and `PathBuf` are imported at file scope, not inside `commands` below: `#[category]`
// hoists that module's contents up to here, so one import of each serves both the module and
// `gg_elevated_rescan`.
use crate::support::treegrep;
use std::path::PathBuf;

/// Re-scan `paths` as root — the elevated half of `gg`'s permission-denied recovery.
/// `#[elevated]` wraps this in a `sudo` self-re-exec round-trip: it generates `GgElevatedRescan`,
/// whose `reexec(…)` (parent, called from `_offer_root_rescan`) spawns `sudo <self> gg-elevated-rescan …`
/// and whose `try_handle()` (child, called from [`crate::run`]) parses that back and runs this.
// The parameters ARE the wire format: `#[elevated]` turns each into a `--flag` the child parses
// back, so bundling them into a struct would take them off the command line the re-exec builds.
#[bashrs_macros::elevated]
#[allow(clippy::too_many_arguments, reason = "one parameter per forwarded flag; see above")]
fn gg_elevated_rescan(expressions: Vec<String>, paths: Vec<PathBuf>, context: usize, delve: bool, no_number: bool, regex: bool, save: Option<PathBuf>, skips: Vec<String>) {
    // `save` is the shared `--save` live file (absent when the run isn't saving); the root pass
    // appends to it and to its `_sorted` sibling, exactly like the main pass.
    let opts = treegrep::Options { line_number: !no_number, context, delve, regex, save, skips };
    treegrep::search(&expressions, &paths, &opts);
}

#[bashrs_macros::category(command = LookupCommand, prefix = "lookup_")]
mod commands {
    use crate::support::args::{GgArgs, GgBase, GrepArgs, SkipArgs};
    use crate::support::{input, preferences, streamgrep};
    use clap::Args;

    /// Search your shell history (case-insensitive, literal) — like `history | grep -iF`
    #[unprefixed]
    #[piped("history")]
    pub fn hg(args: HgArgs) {
        // The wrapper pipes `history` — a bash builtin only the shell itself can produce —
        // into our stdin; we read that stream and filter it in-process.
        let Some(text) = input::bytes_reported("hg", None) else { return };
        let patterns: Vec<String> = args.pattern.into_iter().chain(args.regexp).collect();
        streamgrep::filter(&patterns, &text, &streamgrep::Options::default());
    }

    /// The term to find in your shell history.
    #[derive(Args)]
    pub struct HgArgs {
        /// Term to match (case-insensitive, literal — no regex).
        #[arg(required_unless_present = "regexp")]
        pattern: Option<String>,
        /// Term(s) to match, like `grep -e` — protects a term starting with `-` (e.g. a flag you
        /// once passed); repeatable (OR'd).
        #[arg(short = 'e', long = "regexp", value_name = "PATTERN", allow_hyphen_values = true)]
        regexp: Vec<String>,
    }

    /// Recursive search with `--delve` and `--lean` always on — looks inside binaries we can
    /// decode (video subtitle tracks, `.torrent` text), and skips the machine-written
    /// directories (`_arg_lean_spec` lists them). Please: no `--re`.
    #[name("GG")]
    #[trailing_newline]
    pub fn gg_delve(args: GgArgs) {
        // Force `--delve` and `--lean`. Both are hidden from GG's help/completion (see
        // `cli::HIDDEN_PINNED`) but still accepted; plain bools, so a caller passing one anyway
        // is a harmless no-op. `--skip-pattern` still adds to what `--lean` already skips.
        let skip = SkipArgs { lean: true, ..args.base.skip };
        _gg(&GgArgs { base: GgBase { delve: true, skip, ..args.base }, ..args });
    }

    /// `GG` plus the two extras: `--save` (`-s`, leave sorted results in `deep_search_<time>_sorted`)
    /// and regex (`-E`). The everything-on, all-caps deep search — `--lean`'s skips apply
    /// here too (`_arg_lean_spec` lists them).
    #[name("GGG")]
    #[trailing_newline]
    pub fn ggg(args: GgArgs) {
        let skip = SkipArgs { lean: true, ..args.base.skip };
        _gg(&GgArgs { base: GgBase { delve: true, save: true, regex: true, skip, ..args.base }, ..args });
    }

    /// Read the input, then filter it in-process with the `grep` crate — case-insensitive, literal
    /// by default (`grep -iF`) or as a regex with `-E`, with `-C` context lines around each match,
    /// `-n` line numbers, and `-v` to keep the non-matching lines instead. Matches are coloured only
    /// when writing to a terminal, like `--color=auto`. Backs the generated `g` family.
    pub(crate) fn _grep(args: &GrepArgs) {
        // grep's `-e` semantics: with any `-e`, the positionals stop being patterns — the first
        // one (if given) is the input instead, so `g -e --flag notes.txt` reads notes.txt.
        let (patterns, source) = if args.base.regexp.is_empty() {
            (args.base.pattern.clone().into_iter().collect(), args.base.source.clone())
        } else if args.base.source.is_some() {
            return eprintln!("g: with -e, pass at most one input (a file, inline text, or stdin)");
        } else {
            (args.base.regexp.clone(), args.base.pattern.clone())
        };
        let Some(text) = input::bytes_reported("g", source.as_deref()) else { return };
        let opts = streamgrep::Options {
            context: args.context,
            line_number: args.base.line_number,
            regex: args.base.regex,
            invert: args.base.invert,
        };
        streamgrep::filter(&patterns, &text, &opts);
    }

    /// Build options from the `gg` args (context comes from `-C`), run the recursive search, then
    /// offer a root re-scan of anything that was unreadable. Backs the generated `gg` family (whose
    /// numbered variants pin `-C`) and the hand-written `GG`.
    pub(crate) fn _gg(args: &GgArgs) {
        // The full expression list: positional ones plus any `-e` (grep-style, protecting
        // expressions that start with `-`), all OR'd downstream.
        let expressions: Vec<String> =
            args.base.expressions.iter().chain(&args.base.regexp).cloned().collect();
        let save = if args.base.save {
            let name = format!("deep_search_{}", preferences::datehour_stamp());
            let path = std::env::current_dir().unwrap_or_default().join(name);
            if let Err(err) = std::fs::write(&path, format!("# search term used: {}\n", expressions.join(" "))) {
                return eprintln!("gg: cannot create {}: {err}", path.display());
            }
            Some(path)
        } else {
            None
        };
        let opts = treegrep::Options {
            line_number: !args.base.no_line_number,
            context: args.context,
            delve: args.base.delve,
            regex: args.base.regex,
            save,
            skips: args.base.skip.skips(),
        };
        let roots = [args.base.directory.clone()];
        let denied = treegrep::search(&expressions, &roots, &opts);
        _offer_root_rescan(&expressions, &denied, &opts);
        // `--re`: after the results are on screen, offer to replace every match in place. A
        // distinct, confirmed, destructive phase — never entangled with the read-only search.
        if let Some(replacement) = &args.base.re {
            _replace_matches(&expressions, &roots, &args.base.skip.skips(), args.base.regex, replacement);
        }
        // Runs once, after both passes have appended their sorted sections to the `_sorted` sibling.
        // The live (arrival-order) file is the crash-safety net: only once the sorted copy verifiably
        // exists is it removed, and the notice points at what remains.
        if let Some(live) = &opts.save {
            let sorted = treegrep::sorted_path(live);
            if sorted.exists() {
                let _ = std::fs::remove_file(live);
                eprintln!("\noutput copied in-order to {}", sorted.display());
            } else {
                eprintln!("\ncould not sort the output; raw results remain at {}", live.display());
            }
        }
    }

    /// If some paths were unreadable and we're interactive, offer to re-scan just those as root by
    /// re-exec'ing ourselves under the superuser command, scoped to the denied paths (no dedup — they turned
    /// up nothing on the first pass). Non-interactive runs just note what was skipped.
    fn _offer_root_rescan(
        expressions: &[String],
        denied: &std::collections::BTreeSet<PathBuf>,
        opts: &treegrep::Options,
    ) {
        use std::io::{IsTerminal, Write};
        if denied.is_empty() {
            return;
        }
        if !std::io::stdin().is_terminal() {
            eprintln!("\n{} path(s) skipped (permission denied); run interactively to re-scan as root.", denied.len());
            return;
        }
        eprintln!("\n{} path(s) were unreadable (permission denied):", denied.len());
        // Cap the list so a huge count can't scroll the count/prompt off-screen: show up to 10, or
        // the first 9 plus a summary line when there are more.
        let shown = if denied.len() > 10 { 9 } else { denied.len() };
        for path in denied.iter().take(shown) {
            eprintln!("  {}", path.display());
        }
        if denied.len() > shown {
            eprintln!("  [{} more paths omitted]", denied.len() - shown);
        }
        eprint!("Re-scan them as root? [y/N] ");
        let _ = std::io::stderr().flush();
        let mut answer = String::new();
        if std::io::stdin().read_line(&mut answer).is_err() || !answer.trim().eq_ignore_ascii_case("y") {
            return;
        }
        // `#[elevated]` on `gg_elevated_rescan` generated `GgElevatedRescan`; hand its parent side the
        // tuning and the exact denied paths (as a slice).
        let paths: Vec<PathBuf> = denied.iter().cloned().collect();
        GgElevatedRescan::reexec(expressions, &paths, opts.context, opts.delve, !opts.line_number, opts.regex, opts.save.as_deref(), &opts.skips);
    }

    /// The `--re` phase: plan every in-place replacement, show what it would touch, and apply it
    /// only on an interactive `y`. Destructive and undo-less, so the preview + confirm is the whole
    /// point — and a non-interactive run refuses rather than mutate unattended.
    fn _replace_matches(
        expressions: &[String],
        roots: &[PathBuf],
        skips: &[String],
        regex: bool,
        replacement: &str,
    ) {
        use std::io::{IsTerminal, Write};
        let Some(plan) = treegrep::plan_replacements(expressions, roots, skips, regex, replacement) else {
            return;
        };
        if plan.is_empty() {
            eprintln!("\n--re: nothing to replace.");
            return;
        }
        eprintln!("\n--re would replace every match with \"{replacement}\", in place:");
        _preview("rename", plan.renames.iter().map(|(f, t)| format!("{} → {}", f.display(), t.display())));
        _preview(
            "rewrite",
            plan.rewrites.iter().map(|(p, _, n)| {
                format!("{} ({n} occurrence{})", p.display(), if *n == 1 { "" } else { "s" })
            }),
        );
        if !std::io::stdin().is_terminal() {
            eprintln!("--re: refusing to modify files non-interactively.");
            return;
        }
        eprint!("Apply these changes? [y/N] ");
        let _ = std::io::stderr().flush();
        let mut answer = String::new();
        if std::io::stdin().read_line(&mut answer).is_err() || !answer.trim().eq_ignore_ascii_case("y") {
            eprintln!("--re: aborted — nothing changed.");
            return;
        }
        let (rewritten, renamed, problems) = treegrep::apply_replacements(&plan);
        for problem in &problems {
            eprintln!("--re: {problem}");
        }
        eprintln!("--re: rewrote {rewritten} file(s), renamed {renamed} path(s).");
    }

    /// Print a capped preview list (up to 10, like the root-rescan prompt), one `kind: item` per
    /// line, so a huge change set can't scroll the confirm prompt off-screen.
    fn _preview(kind: &str, items: impl Iterator<Item = String>) {
        let items: Vec<String> = items.collect();
        if items.is_empty() {
            return;
        }
        let shown = if items.len() > 10 { 9 } else { items.len() };
        for item in items.iter().take(shown) {
            eprintln!("  {kind}: {item}");
        }
        if items.len() > shown {
            eprintln!("  [{} more {kind}(s) omitted]", items.len() - shown);
        }
    }
}

#[cfg(test)]
mod pinned_tests {
    use crate::support::args::{GgBase, SkipArgs};

    /// A flag listed in `cli::HIDDEN_PINNED` is hidden from a command's help on the promise that
    /// the command forces it on. Hiding one without setting it is the worst of both: invisible
    /// AND inactive. `GG` shipped exactly that bug for `--lean`, so it is pinned here.
    #[test]
    fn gg_actually_forces_the_flags_it_hides() {
        let base = GgBase {
            expressions: vec!["x".to_string()],
            regexp: Vec::new(),
            directory: std::path::PathBuf::from("."),
            no_line_number: false,
            delve: false,
            regex: false,
            save: false,
            re: None,
            skip: SkipArgs { skip_pattern: vec!["mine".to_string()], lean: false },
        };
        // The same construction `GG` performs on the way to `_gg`.
        let skip = SkipArgs { lean: true, ..base.skip };
        assert!(skip.lean, "GG hides --lean, so it must set it");
        assert!(
            skip.skips().iter().any(|s| s == "mine"),
            "and a user's own --skip-pattern still applies on top"
        );
        assert!(
            skip.skips().iter().any(|s| s == ".git/"),
            "so a GG run really does skip what --lean names"
        );
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::Parser;

    #[test]
    fn gg_elevated_rescan_round_trips_its_argv() {
        // The wire shape `#[elevated]` builds and parses back: the marker (consumed as argv[0] by
        // clap), then a `--flag`/`--flag value` per parameter, with `Vec` parameters repeated.
        let parsed = GgElevatedRescanArgs::parse_from([
            "gg-elevated-rescan",
            "--expressions", "foo", "--expressions", "bar",
            "--paths", "/a", "--paths", "/b",
            "--context", "3", "--delve", "--no-number", "--regex",
            "--save", "/tmp/deep_search_x",
        ]);
        assert_eq!(parsed.expressions, ["foo", "bar"]);
        assert_eq!(parsed.paths, [PathBuf::from("/a"), PathBuf::from("/b")]);
        assert_eq!(parsed.context, 3);
        assert!(parsed.delve && parsed.no_number && parsed.regex);
        assert_eq!(parsed.save, Some(PathBuf::from("/tmp/deep_search_x")));
    }

    #[test]
    fn gg_elevated_rescan_parses_a_plain_run_without_save() {
        // The exact argv `reexec` emits for a non-saving run — the `GG` regression: an `Option`
        // parameter must vanish from the wire entirely, not ride along as an empty sentinel value
        // (clap rejects an empty `PathBuf`, which surfaced as "a value is required for '--save'").
        let parsed = GgElevatedRescanArgs::parse_from([
            "gg-elevated-rescan", "--expressions", "foo", "--paths", "/a", "--context", "0",
        ]);
        assert_eq!(parsed.save, None);
        assert!(!parsed.delve && !parsed.no_number && !parsed.regex);
    }
}
