//! Text-lookup commands: the shell-history search (`hg`) and the loud all-caps deep searches — `GG`
//! (recursive search with `--delve` forced on) and `GGG` (`GG` plus `--save` and `-E` forced too).
//! This module also owns the runners the generated shortcut
//! families forward to — `_grep` for the `g` family and `_gg` for the `gg` family (both in
//! [`crate::categories::autogen_lookup`]) — plus [`gg_elevated_rescan`], the root re-scan routine.
//! Those live here, not in `support`, because the re-scan drives a `sudo` self-re-exec (generated by
//! [`macro@bashrs_macros::elevated`]) that reaches up to [`crate::run`], sitting above the `support`
//! search engines ([`streamgrep`](crate::support::streamgrep), [`treegrep`](crate::support::treegrep));
//! the shared argument structs are in [`crate::support::args`].

// `treegrep` and `PathBuf` are imported at file scope, not inside `commands` below: `#[category]`
// hoists that module's contents up to here, so one import of each serves both the module and
// `gg_elevated_rescan`.
use crate::support::treegrep;
use std::path::PathBuf;

/// Re-scan `paths` as root — the elevated half of `gg`'s permission-denied recovery.
/// `#[elevated]` wraps this in a `sudo` self-re-exec round-trip: it generates `GgElevatedRescan`,
/// whose `reexec(…)` (parent, called from `_offer_root_rescan`) spawns `sudo <self> gg-elevated-rescan …`
/// and whose `try_handle()` (child, called from [`crate::run`]) parses that back and runs this.
#[bashrs_macros::elevated]
fn gg_elevated_rescan(expressions: Vec<String>, paths: Vec<PathBuf>, context: usize, delve: bool, no_number: bool, regex: bool, save: Option<PathBuf>) {
    // `save` is the shared `--save` live file (absent when the run isn't saving); the root pass
    // appends to it and to its `_sorted` sibling, exactly like the main pass.
    let opts = treegrep::Options { line_number: !no_number, context, delve, regex, save };
    treegrep::search(&expressions, &paths, &opts);
}

#[bashrs_macros::category(command = LookupCommand, prefix = "lookup_")]
mod commands {
    use crate::support::args::{GgArgs, GrepArgs};
    use crate::support::{input, preferences, streamgrep};
    use clap::Args;

    /// Search your shell history (case-insensitive, literal) — like `history | grep -iF`
    #[unprefixed]
    #[piped("history")]
    pub fn hg(args: HgArgs) {
        // The wrapper pipes `history` — a bash builtin only the shell itself can produce —
        // into our stdin; we read that stream and filter it in-process.
        let Some(text) = input::bytes_reported("hg", None) else { return };
        streamgrep::filter(&args.pattern, &text, &streamgrep::Options::default());
    }

    /// The term to find in your shell history.
    #[derive(Args)]
    pub struct HgArgs {
        /// Term to match (case-insensitive, literal — no regex).
        pattern: String,
    }

    /// Recursive search with `--delve` always on — also looks inside binaries we can decode (video
    /// subtitle tracks, `.torrent` text). The loud, all-caps sibling of `gg`, à la `UPUP`.
    #[name("GG")]
    #[trailing_newline]
    pub fn gg_delve(args: GgArgs) {
        // Force `--delve`; it's a plain bool, so setting it when the caller already passed it is a
        // harmless no-op.
        _gg(&GgArgs { delve: true, ..args });
    }

    /// `GG` plus the two extras: `--save` (`-s`, leave sorted results in `deep_search_<time>_sorted`)
    /// and regex (`-E`). The everything-on, all-caps deep search.
    #[name("GGG")]
    #[trailing_newline]
    pub fn ggg(args: GgArgs) {
        _gg(&GgArgs { delve: true, save: true, regex: true, ..args });
    }

    /// Read the input, then filter it in-process with the `grep` crate — case-insensitive, literal
    /// by default (`grep -iF`) or as a regex with `-E`, with `-C` context lines around each match,
    /// `-n` line numbers, and `-v` to keep the non-matching lines instead. Matches are coloured only
    /// when writing to a terminal, like `--color=auto`. Backs the generated `g` family.
    pub(crate) fn _grep(args: &GrepArgs) {
        let Some(text) = input::bytes_reported("g", args.source.as_deref()) else { return };
        let opts = streamgrep::Options {
            context: args.context,
            line_number: args.line_number,
            regex: args.regex,
            invert: args.invert,
        };
        streamgrep::filter(&args.pattern, &text, &opts);
    }

    /// Build options from the `gg` args (context comes from `-C`), run the recursive search, then
    /// offer a root re-scan of anything that was unreadable. Backs the generated `gg` family (whose
    /// numbered variants pin `-C`) and the hand-written `GG`.
    pub(crate) fn _gg(args: &GgArgs) {
        let save = if args.save {
            let name = format!("deep_search_{}", preferences::datehour_stamp());
            let path = std::env::current_dir().unwrap_or_default().join(name);
            if let Err(err) = std::fs::write(&path, format!("# search term used: {}\n", args.expressions.join(" "))) {
                return eprintln!("gg: cannot create {}: {err}", path.display());
            }
            Some(path)
        } else {
            None
        };
        let opts = treegrep::Options {
            line_number: !args.no_line_number,
            context: args.context,
            delve: args.delve,
            regex: args.regex,
            save,
        };
        let roots = [args.directory.clone()];
        let denied = treegrep::search(&args.expressions, &roots, &opts);
        _offer_root_rescan(&args.expressions, &denied, &opts);
        // Runs once, after both passes have appended their sorted sections to the `_sorted` sibling.
        // The live (arrival-order) file is the crash-safety net: only once the sorted copy verifiably
        // exists is it removed, and the notice points at what remains.
        if let Some(live) = &opts.save {
            let sorted = treegrep::sorted_path(live);
            if sorted.exists() {
                let _ = std::fs::remove_file(live);
                eprintln!("\noutput copied in-order to {}", sorted.display());
            } else {
                eprintln!("\ncould not sort the output; raw results remain at {}", live.display());
            }
        }
    }

    /// If some paths were unreadable and we're interactive, offer to re-scan just those as root by
    /// re-exec'ing ourselves under the superuser command, scoped to the denied paths (no dedup — they turned
    /// up nothing on the first pass). Non-interactive runs just note what was skipped.
    fn _offer_root_rescan(
        expressions: &[String],
        denied: &std::collections::BTreeSet<PathBuf>,
        opts: &treegrep::Options,
    ) {
        use std::io::{IsTerminal, Write};
        if denied.is_empty() {
            return;
        }
        if !std::io::stdin().is_terminal() {
            eprintln!("\n{} path(s) skipped (permission denied); run interactively to re-scan as root.", denied.len());
            return;
        }
        eprintln!("\n{} path(s) were unreadable (permission denied):", denied.len());
        // Cap the list so a huge count can't scroll the count/prompt off-screen: show up to 10, or
        // the first 9 plus a summary line when there are more.
        let shown = if denied.len() > 10 { 9 } else { denied.len() };
        for path in denied.iter().take(shown) {
            eprintln!("  {}", path.display());
        }
        if denied.len() > shown {
            eprintln!("  [{} more paths omitted]", denied.len() - shown);
        }
        eprint!("Re-scan them as root? [y/N] ");
        let _ = std::io::stderr().flush();
        let mut answer = String::new();
        if std::io::stdin().read_line(&mut answer).is_err() || !answer.trim().eq_ignore_ascii_case("y") {
            return;
        }
        // `#[elevated]` on `gg_elevated_rescan` generated `GgElevatedRescan`; hand its parent side the
        // tuning and the exact denied paths (as a slice).
        let paths: Vec<PathBuf> = denied.iter().cloned().collect();
        GgElevatedRescan::reexec(expressions, &paths, opts.context, opts.delve, !opts.line_number, opts.regex, opts.save.as_deref());
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::Parser;

    #[test]
    fn gg_elevated_rescan_round_trips_its_argv() {
        // The wire shape `#[elevated]` builds and parses back: the marker (consumed as argv[0] by
        // clap), then a `--flag`/`--flag value` per parameter, with `Vec` parameters repeated.
        let parsed = GgElevatedRescanArgs::parse_from([
            "gg-elevated-rescan",
            "--expressions", "foo", "--expressions", "bar",
            "--paths", "/a", "--paths", "/b",
            "--context", "3", "--delve", "--no-number", "--regex",
            "--save", "/tmp/deep_search_x",
        ]);
        assert_eq!(parsed.expressions, ["foo", "bar"]);
        assert_eq!(parsed.paths, [PathBuf::from("/a"), PathBuf::from("/b")]);
        assert_eq!(parsed.context, 3);
        assert!(parsed.delve && parsed.no_number && parsed.regex);
        assert_eq!(parsed.save, Some(PathBuf::from("/tmp/deep_search_x")));
    }

    #[test]
    fn gg_elevated_rescan_parses_a_plain_run_without_save() {
        // The exact argv `reexec` emits for a non-saving run — the `GG` regression: an `Option`
        // parameter must vanish from the wire entirely, not ride along as an empty sentinel value
        // (clap rejects an empty `PathBuf`, which surfaced as "a value is required for '--save'").
        let parsed = GgElevatedRescanArgs::parse_from([
            "gg-elevated-rescan", "--expressions", "foo", "--paths", "/a", "--context", "0",
        ]);
        assert_eq!(parsed.save, None);
        assert!(!parsed.delve && !parsed.no_number && !parsed.regex);
    }
}
