pub mod filesystem;
pub mod media;

use clap::{Parser, Subcommand};
use filesystem::FilesystemCommand;
use media::MediaCommand;

#[derive(Parser)]
#[command(name = "bashrs", about = "Rust-based bashrc")]
pub struct Cli {
    #[command(subcommand)]
    pub command: Command,
}

/// Top-level command set. Each category is flattened so its commands appear
/// directly (e.g. `bashrs lss`), matching the shell functions we generate.
#[derive(Subcommand)]
pub enum Command {
    #[command(flatten)]
    Filesystem(FilesystemCommand),
    #[command(flatten)]
    Media(MediaCommand),
    /// Emit shell function wrappers for every command (used by COMPILE.sh).
    #[command(hide = true)]
    Generate,
}

impl Command {
    pub fn run(self) {
        match self {
            Command::Filesystem(cmd) => cmd.run(),
            Command::Media(cmd) => cmd.run(),
            Command::Generate => print!("{}", wrappers()),
        }
    }
}

/// The command categories, each paired with the label used to group them in the
/// generated `functions.sh`. One row per category — never per command.
fn category_commands() -> [(&'static str, clap::Command); 2] {
    [
        ("filesystem", FilesystemCommand::augment_subcommands(clap::Command::new("filesystem"))),
        ("media", MediaCommand::augment_subcommands(clap::Command::new("media"))),
    ]
}

/// Build the shell function definitions sourced from `~/.bashrs/functions.sh`.
///
/// Definitions are grouped by category, each under a comment header. Every
/// wrapper — including unprefixed aliases — dispatches to the command's *real* name,
/// so an alias is purely a shell-side convenience and never has to resolve as a
/// clap alias. The binary path is inlined into each function rather than held in
/// a shared variable, so sourcing leaves nothing behind in the user's shell.
fn wrappers() -> String {
    // Quoted so `$HOME` expands at call time and paths with spaces stay intact.
    const BIN: &str = "\"$HOME/.bashrs/bashrs\"";

    let mut body = String::new();
    for (label, category) in category_commands() {
        let mut lines = String::new();
        for sub in category.get_subcommands() {
            if sub.is_hide_set() {
                continue; // skip any command marked internal
            }
            let real = sub.get_name();
            for shell_name in std::iter::once(real).chain(sub.get_visible_aliases()) {
                lines += &format!("{shell_name}() {{ {BIN} {real} \"$@\"; }}\n");
            }
        }
        if !lines.is_empty() {
            body += &format!("\n# {label}\n{lines}");
        }
    }

    let mut out = String::from(
        "# Auto-generated by `bashrs generate` — do not edit.\n\
         # Regenerate by re-running COMPILE.sh.\n",
    );
    if !body.is_empty() {
        // Bail early (before defining anything) if the binary isn't present.
        out += &format!("\n[ -f {BIN} ] || return\n");
        out += &body;
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::{Command as ClapCommand, CommandFactory};

    fn command_names<E: Subcommand>() -> Vec<String> {
        E::augment_subcommands(ClapCommand::new("test"))
            .get_subcommands()
            .map(|c| c.get_name().to_string())
            .collect()
    }

    /// Every command in a category must carry its category prefix, unless it is
    /// explicitly listed as an unprefixed exception. This keeps the naming
    /// standard from silently eroding as commands are added.
    fn assert_prefixed(names: &[String], prefix: &str, unprefixed: &[&str]) {
        for name in names {
            assert!(
                name.starts_with(prefix) || unprefixed.contains(&name.as_str()),
                "command `{name}` must start with `{prefix}` or be a declared unprefixed exception in {unprefixed:?}",
            );
        }
    }

    #[test]
    fn cli_definition_is_valid() {
        Cli::command().debug_assert();
    }

    #[test]
    fn filesystem_commands_follow_naming_standard() {
        assert_prefixed(&command_names::<FilesystemCommand>(), "fs_", &[]);
    }

    #[test]
    fn media_commands_follow_naming_standard() {
        assert_prefixed(&command_names::<MediaCommand>(), "media_", &[]);
    }

    #[test]
    fn wrappers_cover_every_command_and_alias() {
        let script = wrappers();
        let has = |line: &str| assert!(script.contains(line), "missing wrapper line: {line}");
        has("fs_lss() { \"$HOME/.bashrs/bashrs\" fs_lss \"$@\"; }"); // prefixed (both)
        has("lss() { \"$HOME/.bashrs/bashrs\" fs_lss \"$@\"; }"); // unprefixed alias ->fs_lss
        has("media_conv() { \"$HOME/.bashrs/bashrs\" media_conv \"$@\"; }"); // prefixed (both)
        has("conv() { \"$HOME/.bashrs/bashrs\" media_conv \"$@\"; }"); // unprefixed alias ->media_conv
        has("media_metadata() { \"$HOME/.bashrs/bashrs\" media_metadata \"$@\"; }");
        has("media_hmerge_imgs() { \"$HOME/.bashrs/bashrs\" media_hmerge_imgs \"$@\"; }");
    }

    #[test]
    fn unprefixed_alias_dispatches_to_the_real_command() {
        // `conv` is a shell-only convenience; it must invoke `media_conv`, not
        // `conv`, so it works regardless of whether clap treats `conv` as valid.
        assert!(wrappers().contains("conv() { \"$HOME/.bashrs/bashrs\" media_conv \"$@\"; }"));
    }

    #[test]
    fn wrappers_group_commands_under_a_category_comment() {
        let script = wrappers();
        // A blank line then a comment introduces each category's block.
        assert!(script.contains("\n# filesystem\n"));
        assert!(script.contains("\n# media\n"));
    }

    #[test]
    fn wrappers_exclude_the_internal_generate_command() {
        assert!(!wrappers().contains("generate() {"));
    }

    #[test]
    fn wrappers_leave_no_variable_behind_in_the_shell() {
        // The path is inlined per function, so sourcing defines functions only —
        // nothing lingers in the user's environment afterward.
        assert!(!wrappers().contains("__bashrs_bin"));
    }

    #[test]
    fn wrappers_bail_early_when_the_binary_is_missing() {
        assert!(wrappers().contains("[ -f \"$HOME/.bashrs/bashrs\" ] || return"));
    }

    /// Guards the small per-category list in `category_commands` against drift:
    /// every command the CLI can dispatch must be grouped into exactly one
    /// category (and vice versa), so none can silently miss a wrapper.
    #[test]
    fn category_grouping_covers_exactly_the_cli_commands() {
        use std::collections::BTreeSet;
        let dispatchable: BTreeSet<String> = Cli::command()
            .get_subcommands()
            .filter(|c| !c.is_hide_set() && c.get_name() != "help")
            .map(|c| c.get_name().to_string())
            .collect();
        let grouped: BTreeSet<String> = category_commands()
            .iter()
            .flat_map(|(_, cmd)| {
                cmd.get_subcommands().map(|c| c.get_name().to_string()).collect::<Vec<_>>()
            })
            .collect();
        assert_eq!(dispatchable, grouped, "every CLI command must belong to exactly one category");
    }
}

/// Exercises the three naming modes of the `#[category]` macro on a throwaway
/// category, so the `#[prefixed]` / `#[unprefixed]` logic is covered directly
/// (the real categories only use the default and the both-forms cases).
#[cfg(test)]
#[allow(dead_code)] // the generated `run`/handlers aren't invoked, only introspected
mod macro_naming_modes {
    use clap::{Command as ClapCommand, Subcommand};

    #[bashrs_macros::category(command = ProbeCommand, prefix = "p_")]
    mod probe {
        use clap::Args;

        /// prefixed by default
        pub fn alpha(_args: Alpha) {}
        #[derive(Args)]
        pub struct Alpha {}

        /// unprefixed only
        #[unprefixed]
        pub fn beta(_args: Beta) {}
        #[derive(Args)]
        pub struct Beta {}

        /// both forms
        #[prefixed]
        #[unprefixed]
        pub fn gamma(_args: Gamma) {}
        #[derive(Args)]
        pub struct Gamma {}
    }

    #[test]
    fn each_mode_yields_the_expected_name_and_aliases() {
        let built = ProbeCommand::augment_subcommands(ClapCommand::new("probe"));
        let aliases = |name: &str| {
            built
                .get_subcommands()
                .find(|c| c.get_name() == name)
                .map(|c| c.get_visible_aliases().map(str::to_string).collect::<Vec<_>>())
        };
        assert_eq!(aliases("p_alpha"), Some(vec![]), "default: prefixed only");
        assert_eq!(aliases("beta"), Some(vec![]), "#[unprefixed]: bare name, no prefix");
        assert_eq!(aliases("p_gamma"), Some(vec!["gamma".to_string()]), "both: prefixed + bare alias");
    }
}
